### ISSUE TITLE
Add --profile and --region flags

### ISSUE THREAD

**Issue by tj** [apex/up#654]
Might as well, FWIW you can also use `AWS_PROFILE` to swap that out if you're not using `.profile` in up.json.

**Comment by kaihendry** [comment]
AH! Now I know what you mean by .profile, I thought you were referring to a filename `~/.profile`! You mean a JSON path!

    jq .profile up.json

I want to keep "foo-dev" in my up.json, since that's what account is uses in development. But come deployment, I want to be able to override it:

```
deploy:
 # demo
 - provider: script
   script: AWS_PROFILE=foo-demo AWS_ACCESS_KEY_ID=$AWS_123401051872_ID AWS_SECRET_ACCESS_KEY=$AWS_123401051872_SECRET up
   skip_cleanup: true
   on:
      branch: master
 # production
 - provider: script
   script: AWS_PROFILE=foo-prod AWS_ACCESS_KEY_ID=$AWS_123458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_123458993663_SECRET up
   skip_cleanup: true
   on:
      branch: master
```

Maybe this works already, need to try it. Otherwise, yeah, I need `--profile` I guess?
