### ISSUE TITLE
Alternative config format(s)

### ISSUE THREAD

**Issue by tj** [apex/up#83]
Not a priority at all but:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/JSON%20is%20fine)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/JSON%20is%20fine/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/YAML)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/YAML/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/TOML)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/TOML/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/HCL)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/HCL/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/Other)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BNDW9KJ3EZ8DCRNQ4KRB2XMG/Other/vote)

**Comment by aaronagray** [comment]
Oops. I didn't realize that clicking would submit my vote, so I voted for TOML. I've never heard of TOML and JSON is fine, in my opinion :D

**Comment by tj** [comment]
I don't mind TOML until it gets to the nested arrays, that gets pretty unintuitive unless you specify it like this which looks weird IMO

```toml
name = "api"
description = "Some API for whatever"

[hooks]

build = "make build"
clean = "make clean"

[environment]

FOO = "here"
BAR = "here"

[cors]

allowed_origins = ["example.com"]
allowed_methods = ["GET"]
max_age = 123123

[lambda]

memory = 1024
timeout = 5

[dns]

zones = [
  {
    name = "apex.sh",
    records = [
      {
        name = "blog.apex.sh",
        type = "CNAME",
        ttl = 300,
        value = ["......."]
      }
    ]
  }
]
```

**Comment by tj** [comment]
could see YAML getting unwieldy too, maybe need to re-shape some of the config to suit these better later

```yaml
name: "api"
description: "Some API for whatever"

hooks:
  build: "make build"
  clean: "make clean"

environment:
  FOO: "here"
  BAR: "here"

cors:
  allowed_origins: ["example.com"]
  allowed_methods: ["GET"]
  max_age: 123123

lambda:
  memory: 1024
  timeout: 5

dns:
  zones:
    - name: "apex.sh"
      records:
        - name: "blog.apex.sh"
          type: "CNAME"
          ttl: 300
          value: ["...."]
```
